# Generated by Django 5.0.6 on 2024-09-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_student_passby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
